- demo/ONNXRuntime/README.md
- docs/train_custom_data.md
Hi, yolox teams,
This PR is just fixing typos and remove the trailing spaces in docs.
> Fixing typo and remove the trailing spaces in docs

- yolox/exp/base_exp.py
- yolox/exp/build.py
special thanks to #9 and its author [zhiliu6](https://github.com/zhiliu6), we could not wait him for suggested change, so we do it ourselves.
> fix(exp): change output_dir in base_exp and fix bug of exp mapping

- yolox/utils/ema.py
Hi, this can help people to do the inference without installing `apex`, especially when the user does not need to train a new model.
> refactor(utils): call apex in is_parallel

- .gitignore
- README.md
- docs/train_custom_data.md
- requirements.txt
- tools/export_onnx.py
- For exporting simplified ONNX model, `os.system()` method is not recommended as it is calling `python3` which is not the default alias for many people.
- `requirements.txt` doesn't points to exact module versions hence can break in future. Request the maintainer to add `==` or `>=` while adding python module versions.
- Fixed Training Docs
> Potential Bug fixes and Docs update

- yolox/models/yolo_head.py
Skip to save unused tensor in dynamic_k_matching function for saving memory usage
Actually, I didn't profile the memory usage of this function after modifying code.
> Skip to save unused tensor in dynamic_k_matching function

- setup.py
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "D:\deep\yolox-cake\setup.py", line 51, in <module>
long_description = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x90 in position 425: illegal multibyte sequence
> Fix compile error in Windows environment

- docs/model_zoo.md
There are typos for YOLOX-Tiny and YOLOX-Nano download paths.
YOLOX-Tiny -> [https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_tiny.pth](https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_tiny.pth)
YOLOX-Nano -> [https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_nano.pth](https://github.com/Megvii-BaseDetection/YOLOX/releases/download/0.1.1rc0/yolox_nano.pth)
> fix model zoo YOLOX-Tiny & YOLOX-Nano path

- yolox/data/data_augment.py
@Joker316701882 
I think that we don't need to copy bboxes process in this function.
Could you review it?
> skip copying bboxes in horizontal flip augmentation for speedup

- yolox/models/yolo_head.py
avoid `RuntimeError: "sigmoid_cpu" not implemented for 'Half'`
```
File ".\YOLOX\yolox\models\yolo_head.py", line 203, in forward
dtype=xin[0].dtype,
└ <unprintable tuple object>
File ".\YOLOX\yolox\models\yolo_head.py", line 357, in get_losses
"cpu",
File "..\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
return func(*args, **kwargs)
│     │       └ {}
│     └ <unprintable tuple object>
└ <function YOLOXHead.get_assignments at 0x000001E906CFDA68>
File ".\YOLOX\yolox\models\yolo_head.py", line 492, in get_assignments
* obj_preds_.unsqueeze(0).repeat(num_gt, 1, 1).sigmoid_()
│          │                   └ 84
│          └ <method 'unsqueeze' of 'torch._C._TensorBase' objects>
└ tensor([[-4.2734],
[-5.5000],
[-7.6758],
...,
[-3.6504],
[-8.5625],
[-8.9297]... …
```
> fix yolo_head.py not support fp16 when fallback to cpu mode

- docs/train_custom_data.md
I don't seem to find any refence in code for `mscale`. Isn't this a typo for `mosaic_scale`?
> mscale -> mosaic_scale

- tools/trt.py
to avoid
```
[TensorRT] ERROR: Parameter check failed at: engine.cpp::enqueue::387, condition: batchSize > 0 && batchSize <= mEngine.getMaxBatchSize(). Note: Batch size was: 64, but engine max batch size was: 1
```
and avoid the program be kill because of OOM
> support setting max batch/workspace size when convert to trt

- demo/ncnn/android/app/src/main/jni/yoloXncnn_jni.cpp
I see that cpp files [got updated](https://github.com/Megvii-BaseDetection/YOLOX/commit/c9fe0aae2db90adccc90f7e5a16f044bf110c816#diff-b5a8b82fceb816f137534cec9693446fe01937042e0810162a529ea13f29bf63) but android version didn't.
- Remove normalization (like in cpp version)
- Convert and feed BGR image
> Remove normalization and convert to BGR

- demo/ncnn/cpp/README.md
In this [tutorial](https://yolox.readthedocs.io/en/latest/demo/ncnn_cpp_readme.html):
```shell
./onnx2ncnn yolox.onnx yolox.param yolox.bin
```
this command outputs `yolox.param` and  `yolox.bin` lately to be optimized by `ncnnoptimize`, and so in:
```shell
../ncnnoptimize model.param model.bin yolox.param yolox.bin 65536
```
`model.param` and `model.bin` do not exist, since they were named differently.
> minor - change ncnn output names in cpp tutorial

- pyproject.toml
Since `setup.py` imports `torch`
https://github.com/Megvii-BaseDetection/YOLOX/blob/6819425e78e28926d132863d4be20811729c9d44/setup.py#L8
installing `yolox` requires a separate install of `torch` beforehand (as documented in the [README](https://github.com/Megvii-BaseDetection/YOLOX#quick-start)). However, there is a standard way to include build dependencies for a Python package. From the [PyPA docs](https://packaging.python.org/tutorials/packaging-projects/#creating-pyproject-toml):
> pyproject.toml tells build tools (like pip and build) what is required to build your project.
Adding `pyproject.toml` with a `build-system.requires` section that includes `torch` would eliminate the need to install `torch` with a separate command prior to installing `yolox`. (Importantly, this only installs …
> Add torch to build requirements

- pyproject.toml
Reverts Megvii-BaseDetection/YOLOX#682, pyproject.toml might cause cache problem during  `pip install`.
> revert "Add torch to build requirements"

- tools/eval.py
- yolox/evaluators/coco_evaluator.py
support logging per category mAP value.
close some issues like #385 .
> feat(evaluator): support logging per class mAP during evaluation

- yolox/data/datasets/coco.py
Due to removing useless anno object, this PR could save about 30% memory when using COCO dataset.
> chore(data): save memory for COCO dataset

- yolox/models/darknet.py
there's a typo in ./yolox/models/darknet.py
> Correct typo

- demo/MegEngine/python/demo.py
- demo/ONNXRuntime/onnx_inference.py
- demo/OpenVINO/python/openvino_inference.py
- tools/demo.py
- yolox/data/datasets/coco.py
- yolox/data/datasets/voc.py
Initial PR proposed here: https://github.com/Megvii-BaseDetection/YOLOX/pull/1070 but Owner prefers to stick with os.path library.
This new PR should provide the same fix.
- Replaced hard coded `/` with os.path functions.
> Fix path issues with Windows

- tools/trt.py
torch2trt does a forward pass with the model and inputs and if autograd is not disabled it consumes a lot of memory to keep track of intermediary operation results for the backward pass. torch2trt never calls `backward()` so all that memory is used for nothing.
This PR disables autograd during Tensor RT conversion. This should particularly help conversion on edge devices with low memory and reduce the need to change the workspace size as in: #627, #756, #496, ...
> Disable autograd during TensorRT conversion

- yolox/data/datasets/voc.py
Cause string of float like "100.1" can't change to int directly in python, so it will throw an error when the num of bbox is float in this code. Actually, I got the error when using and it can work after changing like this.
> An error about type conversion

- exps/default/yolox_tiny.py
If used for single scale training, the input_size should be 416 in yolox_tiny.  
The input_scale looks like a typo, although it does not affect multi-scale training.
BTW, I think it's better to provide both multi-scale and single-scale training model modelzoo. 
Thanks.
> fix tiny config input_size

- yolox/evaluators/coco_evaluator.py
Eval extract class names from dataset. It allows to evaluate models on datasets with classes different from coco.
> Support eval with custom dataset

- tools/demo.py
This PR adds the possibility to run YOLOX live on web camera - showing the detections in a "live" window. I had to do some minor fixes as it always changed the save-path even it was not intended to save the results. Therefore the PR is somewhat bigger than needed - so it also fix a minor other issue.
` python tools/demo.py webcam -n yolox-l -c yolox_l.pth --camid 0 --conf 0.25 --nms 0.45 --tsize 640 --device cpu`
Will now give a result like this (running on a GPU less MacBook):
> added ability to show YOLOX demo in live window

- yolox/utils/metric.py
When we set enviroment variable `CUDA_VISIBLE_DEVICES`, pytorch sees only specified gpus and [`get_total_and_free_memory_in_Mb(cuda_device)`](https://github.com/Megvii-BaseDetection/YOLOX/blob/57309c730d9f8c0dd1496706886ec00ddc8a11d2/yolox/utils/metric.py#L22) doesn't work properly.
For example, let `CUDA_VISIBLE_DEVICES=2`. [`get_local_rank()`](https://github.com/Megvii-BaseDetection/YOLOX/blob/57309c730d9f8c0dd1496706886ec00ddc8a11d2/yolox/utils/dist.py#L98) will return 0. It makes [`get_total_and_free_memory_in_Mb(cuda_device)`](https://github.com/Megvii-BaseDetection/YOLOX/blob/57309c730d9f8c0dd1496706886ec00ddc8a11d2/yolox/utils/metric.py#L22) measure memory of zero gpu, not the second. If gpu 0 is occupied by other process, the error occurs, like in #193, #346, #438
> fix(utils): occupy_mem based on CUDA_VISIBLE_DEVICES

- yolox/data/datasets/coco.py
This allows the following command to be run without error when database and config files are deployed:
"python -m yolox.tools.eval -n  yolox-s -c yolox_s.pth -b 64 --conf 0.001 -d 1 --test"
> Fix the error when running Yolox evaluation on COCO test-dev

- docs/quick_run.md
- tools/train.py
- yolox/core/trainer.py
- yolox/utils/__init__.py
- yolox/utils/logger.py
This PR fixes issues #1030 and #1049 . It adds support for the wandb logger.
I've added a new command line argument `--logger` which accepts "tensorboard" and "wandb" as arguments and raises an error otherwise.
More wandb related arguments like `project`, `entity` etc. can be provided in the CLI using the prefix `wandb-`. For example
```shell
python tools/train.py -n yolox-s -d 8 -b 64 --fp16 -o [--cache] --logger wandb wandb-project <project name>
yolox-m
yolox-l
yolox-x
```
All the metrics are logged to the W&B dashboard along with the hyperparameters. The model checkpoints are stored as wandb artifacts along with tagging the best and latest models appropriately.
[This dashboard](https://wandb.ai/manan-goel/yolox-s/runs/1mg3zu90) uses yolox-tiny.
> Adding support for wandb

- README.md
- docs/freeze_module.md
- tests/__init__.py
- tests/utils/test_model_utils.py
- yolox/core/trainer.py
- yolox/exp/yolox_base.py
- yolox/utils/model_utils.py
close #1105 , I add UT for `adjust_status` also.
Simple example code for users who want to freeze backbone.
```
class Exp(MyExp):
...
def get_model(self):
from yolox.utils import freeze_module
model = super().get_model()
freeze_module(model.backbone.backbone)
return model
```
Plz review kindly. @GOATmessi7 @Joker316701882
> feat(utils): freeze module

- hubconf.py
- yolox/models/__init__.py
- yolox/models/build.py
- yolox/models/yolo_head.py
- yolox/utils/__init__.py
- yolox/utils/compat.py
It's two seprate PR, plz don't squash.
Plz review kindly @GOATmessi7 @Joker316701882
> feat(model): support hub load

- docs/train_custom_data.md
Correction of URL pointing to `base_exp.py` instead of `yolox_base.py`
> fix: Link to `yolox_base.py`

- demo/TensorRT/cpp/logging.h
Hello, I'm maintaining [YOLOX-ROS](https://github.com/Ar-Ray-code/YOLOX-ROS).
I open a pull request to suggest additional support for Jetson + [TensorRT-C++ demo](https://github.com/Megvii-BaseDetection/YOLOX/tree/main/demo/TensorRT/cpp), error in the demo program and how to work that.
---
- Board : Jetson Nano
- Jetpack : 32.6.1 (Ubuntu 18.04, CUDA 10.2)
Modify [logging.h](https://github.com/Megvii-BaseDetection/YOLOX/blob/main/demo/TensorRT/cpp/logging.h#L239) according to the URL.
https://forums.developer.nvidia.com/t/looser-throw-specifier-for-virtual-void-logger-log/187963
This is a very minor correction, but please correct it for the sake of beginners. :)
> Fix logging.h for Jetson

- yolox/core/trainer.py
As mentioned in #1144 
Logger wandb accepts options start with `wandb-`
But currently the code with `lstrip` will delete other characters after `wandb-` (e.g. `wandb-name` will become `me`)
Here's a simple fix I use.
> Fixed option key be messed issue in wandb option parsing.

- hubconf.py
- yolox/models/build.py
I've added a possibility to load a custom YOLOX model with torch.hub from a checpotint and an exp files. Not gonna lie, it's inspired by https://github.com/ultralytics/yolov5, but I made it from scratch keeping original codestyle.
Added functionality also lets us load our own trained model without additional hussle.
I've removed some parameters from the original  `create_yolox_model` function and all the functions using it. I might add them back in the future for additional functionality, if you wish. 
Though, I doubt anyone loads a non-pretrained model with `torch.hub.load` because you've provided us with a training script. 
The `num_classes` was completely redundant.
I believe that this is a quality of life commit this repo needs.
> feat(hubconf, build): loading a custom model with `torch.hub.load`

- tools/export_torchscript.py
I would like to add the `decode_in_inference` option to export_torchscript.py. The reason is the same as #1113.
I have confirmed that it can be converted torchscript properly with this option set to True.
Can you please review this PR?
> Add option decode_in_inference to export_torchscript

- yolox/models/yolo_head.py
Replace `ScatterND` ops that will cause error in openvino model optimizer with more acceptable `Concat`. Now you can embed decoder into OpenVINO Intermediate Representation format (IR), which you can infer later with OpenVINO™ Runtime.
> Optimize decode_outputs for OpenVINO IR

- requirements.txt
- tools/export_onnx.py
I'm the author of onnx-simplifier. Recently I published onnxsim v0.4.1. In the latest version, dynamic input shapes are natively supported with no need for extra flags like `dynamic_input_shapes` and `input_shapes`.
> upgrade onnxsim to v0.4.1

- yolox/models/yolo_head.py
This PR is tested on YOLOX-tiny and YOLOX-S.
Before (single-node, COCO val set, bs 64):
YOLOX-tiny: 31.6 mAP
YOLOX-small: 40.1 mAP
After (single-node, COCO val set, bs 64):
YOLOX-tiny: 31.6 mAP
YOLOX-small: 40.6 mAP
> fix(head): fix no-candidate anchor issue for tiny objects during label assignment

- yolox/exp/base_exp.py
As mentioned in #1613 tuple and list arguments are not supported by the merge function. This PR adds support for both of them and even converts the values directly into the source format.
Example:
```
python tools/train.py -f myexperiment.py -d 1 -b 64 input_size "512, 512"
```
> Add sequence support for experiment options merge function #1613

- demo/TensorRT/cpp/yolox.cpp
Hi,
This merge request update the name of input & output blob name.
It allow to run tensorrt onnx models converted using `trtexec --onnx=yolox_s.onnx --saveEngine=yolox_s.trt`
Best Regards,
Michel.
> Update yolox.cpp: fix INPUT_BLOB_NAME & OUTPUT_BLOB_NAME

- demo/TensorRT/cpp/README.md
- demo/TensorRT/cpp/yolox.cpp
Revert #1786 to fix compat issue.
update doc to help those are using `trtexec`.
> fix(demo): revert #1786 and update trt doc

- .github/workflows/ci.yaml
fix reason: check [url](https://github.com/actions/runner-images/issues/11101)
remove python 3.7 since it's EOL.
> fix: update image os version
