Megvii-BaseDetection/YOLOX

- README.md
- demo/ncnn/android/README.md
- docs/train_custom_data.md
> fix(docs): update ncnn README and fix typo

- README.md
- docs/train_custom_data.md
- exps/example/yolox_voc/yolox_voc_s.py
- yolox/data/datasets/__init__.py
- yolox/evaluators/__init__.py
fix voc dataloader and some typos in README
> fix voc dataloader

- exps/example/yolox_voc/yolox_voc_s.py
- yolox/exp/yolox_base.py
> fix(data): fix sampler bug for single device

- README.md
Delete a redundant </details> in README.md
> [Fix]: Delete redundant </details> in README.md

- yolox/utils/setup_env.py
Some issue are related to resources in python3, especially on different OS system. This pr is aim to fix such issues.
> fix(utils): change logic of setup_env to provide better feeling

- demo/ONNXRuntime/onnx_inference.py
- demo/OpenVINO/python/openvino_inference.py
- yolox/utils/demo_utils.py
> fix multiclass_nms bug

- demo/OpenVINO/cpp/yolox_openvino.cpp
- demo/TensorRT/cpp/yolox.cpp
- demo/ncnn/cpp/yolox.cpp
- tools/demo.py
> Fix cpp return and demo trt bug

- tools/train.py
- yolox/core/launch.py
- yolox/data/datasets/mosaicdetection.py
- yolox/utils/boxes.py
- yolox/utils/metric.py
- yolox/utils/setup_env.py
This reverts commit 9ac889 to fix training bug
> revert "chore(core): update launch backend to subprocess (#158)"

- yolox/data/datasets/datasets_wrapper.py
related to #85 
Thx for https://www.zhihu.com/question/473350307/answer/2024804311
> Fix(core): fix mosaic bug

- tools/train.py
Default needs to be set to False, for the option to have any effect at all
> Fix --fp16 option

- demo/MegEngine/python/models/yolo_head.py
- yolox/models/yolo_head.py
remove an unused member variable  self.expanded_strides
> remove an unused member variable  self.expanded_strides

- exps/default/yolov3.py
- yolox/data/datasets/voc.py
> update exps' import

- demo/TensorRT/cpp/yolox.cpp
size adaptive blobFromImage function
> input image size adaptive blobFromImage function

- demo/ncnn/cpp/README.md
- demo/ncnn/cpp/yolox.cpp
> fix(demo): update yolox.cpp in ncnn

- README.md
- tools/eval.py
- tools/train.py
- yolox/core/launch.py
- yolox/core/trainer.py
- yolox/utils/__init__.py
- yolox/utils/ema.py
- yolox/utils/setup_env.py
switch backend to spawn, which is recommanded in pytorch.
MultiMachine training implemention is not well written in YOLOX, it should be an internal code.So I remove those code. FYI @ruinmessi
> chore(core): switch backend to spawn

- .gitignore
append trt engine file(*.engine) to .ignore
> append trt engine file(*.engine) to .ignore

- demo/OpenVINO/cpp/yolox_openvino.cpp
https://github.com/Megvii-BaseDetection/YOLOX/issues/532
> fix bug in yolox_openvino.cpp

- demo/MegEngine/cpp/README.md
Update megengine link due to breaking change in YOLOX.
PTAL @ruinmessi @Joker316701882
> fix(demo): fix megengine ref link

- docs/updates_note.md
> fix typo in updates_note

- tools/export_torchscript.py
```
python tools/export_torchscript.py --output-name yolox_s.torchscript.pt -n yolox-s -c yolox_s.pth
```
用法文档后面再发pr补
> export torchscript

- tools/train.py
> spelling mistake

- yolox/models/losses.py
> fix(loss): fix the wrong implementation of GIoU

- yolox/models/yolo_head.py
- yolox/utils/boxes.py
COCO train time: 
Before: 1 day, 22:00:54 
After:    1 day, 17:50:37
(64 CPUs, 8GPUs, 64 batch_size, fp16, no cache)
> Optimization of dynamic_k_matching and bboxes_iou

- tools/eval.py
- yolox/evaluators/coco_evaluator.py
- yolox/exp/yolox_base.py
It is not only adapted to the COCO dataset, but also to the dataset of the COCO format type.
> Adapt to COCO format dataset

- yolox/core/trainer.py
- yolox/data/data_augment.py
- yolox/exp/yolox_base.py
PTAL @GOATmessi7  @Joker316701882
> fix(core): avoid overwrite best ckpt

- README.md
added link for web demo on hugging face spaces by https://huggingface.co/Sultannn
> Web Demo link on Hugging Faces Spaces

- README.md
`num-machines` -> `num_machines`
`machine-rank` -> `machine_rank`
> fix(docs) #1121

- setup.py
- yolox/data/datasets/coco.py
- yolox/data/datasets/voc.py
> fix(setup): cpp extension

- .pre-commit-config.yaml
- tools/train.py
- yolox/core/trainer.py
- yolox/exp/yolox_base.py
Plz review @GOATmessi7 @Joker316701882
> feat(exp): get_trainer method, add pre-commit

- README.md
Add third-party resources for StreamYOLO.
> Add third-party resources for StreamYOLO

- docs/model_zoo.md
> Use absolute URLs for model names in docs

- yolox/utils/logger.py
> fix(logger): missing attribute when using colab

- README.md
> Update links for YOLOX-Nano.

- README.md
Add ModelScope link of YOLOX-s and YOLOX-Nano.
> Add ModelScope link

- yolox/models/yolo_head.py
```python
import torch
rand_input_cuda = torch.randint(low=0, high=10, size=(10000, )).cuda()
rand_input_cpu = torch.randint(low=0, high=10, size=(10000, ))
def test1(input):
if (input > 1).sum()  > 0:
return True
def test2(input):
if input.max() > 1:
return True
%timeit test1(rand_input_cuda)
%timeit test1(rand_input_cpu)
%timeit test2(rand_input_cuda)
%timeit test2(rand_input_cpu)
```
> Faster computation to find overlapped anchor

- .gitignore
- demo/ONNXRuntime/README.md
- demo/ONNXRuntime/onnx_inference.py
- demo/OpenVINO/python/openvino_inference.py
- requirements.txt
- yolox/evaluators/voc_eval.py
- yolox/exp/default/__init__.py
- yolox/tools/__init__.py
- yolox/utils/demo_utils.py
This PR solves the following issue:
* github alter onnx version
* compile bug when using python3.10
* np.bool deprecated bug due to np upgrade
PTAL @Joker316701882
> fix(yolox): some bugs due to upgrade

- tools/train.py
- yolox/exp/__init__.py
- yolox/exp/base_exp.py
- yolox/exp/yolox_base.py
- yolox/utils/logger.py
> feat(exp): support iterable type merge

- README.md
> fix(doc): update Dr.Sun's homepage to google scholar
